In [2]:
import numpy as np

# Create a 1-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])

# Create a 2-dimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Create an array of zeros
zeros_arr = np.zeros((3, 4))  # 3 rows, 4 columns

# Create an array of ones
ones_arr = np.ones((2, 2))  # 2 rows, 2 columns

# Create an array with a range of values
range_arr = np.arange(0, 10, 2)  # start from 0, step by 2, stop before 10

# Create a random array
random_arr = np.random.random((2, 3))  # 2 rows, 3 columns with random values
print(random_arr)

[[0.54587236 0.91254651 0.2225789 ]
 [0.04911197 0.23822368 0.39996395]]


Training data shape: (80, 8)
Training labels shape: (80,)
Testing data shape: (20, 8)
Testing labels shape: (20,)

Column Distributions in Train Data:
Column 1: 52.23%
Column 2: 48.01%
Column 3: 47.04%
Column 4: 52.42%
Column 5: 49.12%
Column 6: 48.99%
Column 7: 52.59%
Column 8: 49.50%


# NumPy Indexing and Slicing

In [ ]:
import numpy as np

# Creating a 1-dimensional array
arr = np.array([1, 2, 3, 4, 5])

# Accessing elements
print(arr[0])  # Output: 1
print(arr[2])  # Output: 3

# Slicing
print(arr[1:4])  # Output: [2 3 4]
print(arr[:3])   # Output: [1 2 3]
print(arr[2:])   # Output: [3 4 5]
print(arr[:])    # Output: [1 2 3 4 5]

# Modifying elements using indexing
arr[3] = 8
print(arr)  # Output: [1 2 3 8 5]

# Creating a 2-dimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements
print(arr2[0, 1])  # Output: 2
print(arr2[2, 0])  # Output: 7

# Slicing
print(arr2[1:3, 1:3])
# Output:
# [[5 6]
#  [8 9]]

# Modifying elements using indexing
arr2[1, 2] = 10
print(arr2)
# Output:
# [[ 1  2  3]
#  [ 4  5 10]
#  [ 7  8  9]]


1
3
[2 3 4]
[1 2 3]
[3 4 5]
[1 2 3 4 5]
[1 2 3 8 5]
2
7
[[5 6]
 [8 9]]
[[ 1  2  3]
 [ 4  5 10]
 [ 7  8  9]]


# Numpy Stacking

## Column Stacking

In [9]:
import numpy as np

# Create two 1-dimensional arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Column stacking
result = np.column_stack((array1, array2))

print("Column Stacking 1:")
print(result)


# Create two 2-dimensional arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Column stacking
result = np.column_stack((array1, array2))

print("Column Stacking 2:")
print(result)


Column Stacking 1:
[[1 4]
 [2 5]
 [3 6]]
Column Stacking 2:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## Row Stacking

In [7]:
import numpy as np

# Create two 1-dimensional arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Row stacking
result = np.row_stack((array1, array2))

print("Row Stacking 1:")
print(result)

# Create two 2-dimensional arrays
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Column stacking
result = np.row_stack((array1, array2))

print("Row Stacking 2:")
print(result)


Row Stacking 1:
[[1 2 3]
 [4 5 6]]
Row Stacking 2:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


1. Note that both arrays should have the same number of rows for column stacking to work properly. 

2. Note that both arrays should have the same number of columns for row stacking to work properly. 


# Code Demo: Stacking

In [20]:
import numpy as np

# Step 1: Create combined_data and combined_labels
combined_data = np.random.randint(1, 100, size=(100, 8))
combined_labels = np.random.randint(0, 2, size=(100,))

# Step 2: Splitting the data into training and testing sets
split_ratio = 0.8  # 80% for training, 20% for testing
split_index = int(len(combined_data) * split_ratio)

# Training set
train_data = combined_data[:split_index]
train_labels = combined_labels[:split_index]

# Testing set
test_data = combined_data[split_index:]
test_labels = combined_labels[split_index:]

# Calculate percentile for each column in train_data
column_percentiles = np.percentile(train_data, q=[25, 50, 75], axis=0)

# Print the shapes of the training and testing sets
print("Training data shape:", train_data.shape)
print("Training labels shape:", train_labels.shape)
print("Testing data shape:", test_data.shape)
print("Testing labels shape:", test_labels.shape)
print("Column Percentiles shape:", column_percentiles.shape)

# Print the percentiles for each column in the training set
print("\nColumn Percentiles in Train Data:")
for column_index in range(train_data.shape[1]):
    percentiles = column_percentiles[:, column_index]
    print("Column {}: 25th percentile: {:.2f}, 50th percentile: {:.2f}, 75th percentile: {:.2f}".format(
        column_index + 1, percentiles[0], percentiles[1], percentiles[2]))




Training data shape: (80, 8)
Training labels shape: (80,)
Testing data shape: (20, 8)
Testing labels shape: (20,)
Column Percentiles shape: (3, 8)

Column Percentiles in Train Data:
Column 1: 25th percentile: 29.00, 50th percentile: 50.00, 75th percentile: 75.25
Column 2: 25th percentile: 27.75, 50th percentile: 62.00, 75th percentile: 81.00
Column 3: 25th percentile: 29.75, 50th percentile: 56.50, 75th percentile: 83.00
Column 4: 25th percentile: 28.00, 50th percentile: 48.00, 75th percentile: 72.00
Column 5: 25th percentile: 24.25, 50th percentile: 49.00, 75th percentile: 76.25
Column 6: 25th percentile: 26.50, 50th percentile: 49.00, 75th percentile: 75.50
Column 7: 25th percentile: 34.50, 50th percentile: 60.00, 75th percentile: 79.00
Column 8: 25th percentile: 26.00, 50th percentile: 48.50, 75th percentile: 75.25


In [21]:
train_data[:, 1] > 75.25

array([ True,  True, False,  True, False,  True,  True,  True,  True,
       False, False, False, False, False,  True, False, False, False,
        True,  True,  True, False, False, False,  True,  True, False,
       False, False, False, False,  True, False,  True, False,  True,
       False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False,  True, False,  True,
       False,  True, False, False,  True, False, False, False, False,
        True, False,  True,  True, False, False, False, False, False,
        True, False,  True,  True, False,  True,  True, False])

In [28]:
train_data[:, 1]

array([93, 89, 12, 85, 20, 81, 81, 77, 97, 21, 31, 20, 36, 23, 86, 56, 30,
       32, 95, 77, 89, 75, 62, 26, 81, 83, 75, 52, 63, 45, 44, 89, 29, 83,
        2, 84, 61, 16, 80, 40, 28, 80, 62, 48, 20, 90,  9, 59, 13, 11, 10,
       80, 72, 80, 11, 91, 23, 27, 77, 23, 19, 62, 51, 95, 30, 86, 98, 63,
       74,  4,  7, 40, 93, 75, 78, 81, 47, 82, 85, 73])

In [26]:
abnormal_data = train_data[train_data[:, 1] > 75.25]

In [27]:
abnormal_data

array([[76, 93, 10, 84, 67, 44,  1, 30],
       [32, 89, 18, 39, 14, 46, 59, 97],
       [18, 85, 57, 82, 27, 65, 99,  6],
       [98, 81, 55, 38, 77, 64, 33, 59],
       [13, 81, 46, 23, 29,  1, 86, 74],
       [ 2, 77, 91, 70, 49, 46, 69, 55],
       [25, 97, 95, 69, 70, 61, 12, 12],
       [56, 86, 21, 27, 21, 13, 41, 61],
       [29, 95, 55, 17, 26, 41, 28, 35],
       [83, 77, 22, 97,  5, 82, 94, 57],
       [94, 89, 91, 55, 87,  4, 46, 40],
       [53, 81, 91, 30, 25, 10, 65, 33],
       [23, 83, 55, 61, 21, 94, 29, 25],
       [61, 89, 89, 74, 92, 97, 76,  3],
       [83, 83, 86, 13, 48, 40, 91, 11],
       [53, 84, 43, 29,  2,  8, 50, 72],
       [71, 80, 41, 28,  5, 75, 47, 75],
       [50, 80, 35, 81, 96, 11, 92, 24],
       [83, 90, 29, 69, 71,  4, 58, 64],
       [75, 80, 64, 63, 78, 36, 62, 42],
       [31, 80, 82, 92, 38, 21, 37, 36],
       [39, 91, 77, 19, 91, 31,  1, 48],
       [91, 77, 86, 34, 21, 90, 51, 86],
       [92, 95, 38, 88, 25, 82, 19, 93],
       [39, 86, 

# Code Demo: Slicing and other NumPy operations

In [2]:
import numpy as np

# Step 1: Create the matrix
matrix = np.arange(1, 21).reshape(4, 5)
print("Matrix:", matrix)

# Step 2: Extract the second row
row2 = matrix[1, :]
print("Row 2:", row2)

# Step 3: Extract the last column
col5 = matrix[:, -1]
print("Column 5:", col5)

# Step 4: Change the value at the intersection of the third row and fourth column
matrix[2, 3] = 99

# Step 5: Create the diagonal array
diagonal = np.diagonal(matrix)
print("Diagonal:", diagonal)

# Step 6: Calculate the sum of all elements
total_sum = np.sum(matrix)
print("Sum:", total_sum)

# Step 7: Calculate the mean of each row
row_means = np.mean(matrix, axis=1)
print("Row Means:", row_means)

# Step 8: Calculate the maximum value in each column
col_max = np.max(matrix, axis=0)
print("Column Max:", col_max)

# Step 9: Calculate the minimum value in each row
row_min = np.min(matrix, axis=1)
print("Row Min:", row_min)


Matrix: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
Row 2: [ 6  7  8  9 10]
Column 5: [ 5 10 15 20]
Diagonal: [ 1  7 13 19]
Sum: 295
Row Means: [ 3.  8. 30. 18.]
Column Max: [16 17 18 99 20]
Row Min: [ 1  6 11 16]


Training data shape: (80, 8)
Training labels shape: (80,)
Testing data shape: (20, 8)
Testing labels shape: (20,)
