# 1. Creating an Array

In [ ]:
import numpy as np

# Create a 1-dimensional array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)  # Output: [1 2 3 4 5]

# Create a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Create an array with a specified data type
arr_float = np.array([1, 2, 3], dtype=float)
print(arr_float)  # Output: [1. 2. 3.]


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[1. 2. 3.]


## Creating an array from a Python list:

In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)


[1 2 3 4 5]


## Creating a multidimensional array from nested lists:

In [ ]:
import numpy as np

my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_array = np.array(my_list)
print(my_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Creating an array with a specified data type

In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list, dtype=np.float32)
print(my_array)


[1. 2. 3. 4. 5.]


## Creating an array with a range of values:

In [ ]:
import numpy as np

my_array = np.arange(1, 10, 2)
print(my_array)


[1 3 5 7 9]


## Creating an array with zeros:

In [ ]:
import numpy as np

my_array = np.zeros(5)
print(my_array)


[0. 0. 0. 0. 0.]


## Creating an array with ones:

In [ ]:
import numpy as np

my_array = np.ones((3, 4))
print(my_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 2. Array Arithmetic

## Element-wise operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
result = a + b  # [5, 7, 9]

# Subtraction
result = a - b  # [-3, -3, -3]

# Multiplication
result = a * b  # [4, 10, 18]

# Division
result = a / b  # [0.25, 0.4, 0.5]


## Scalar operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

# Addition
result = a + 5  # [6, 7, 8]

# Subtraction
result = a - 2  # [-1, 0, 1]

# Multiplication
result = a * 3  # [3, 6, 9]

# Division
result = a / 2  # [0.5, 1.0, 1.5]


# Matrix Operations

In [ ]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Matrix multiplication
result = np.dot(a, b)  # [[19, 22], [43, 50]]

# Element-wise matrix multiplication
result = np.multiply(a, b)  # [[5, 12], [21, 32]]

# Matrix exponentiation
result = np.linalg.matrix_power(a, 3)  # [[37, 54], [81, 118]]
