# 1. Creating an Array

In [ ]:
import numpy as np

# Create a 1-dimensional array
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d)  # Output: [1 2 3 4 5]

# Create a 2-dimensional array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2d)
# Output:
# [[1 2 3]
#  [4 5 6]]

# Create an array with a specified data type
arr_float = np.array([1, 2, 3], dtype=float)
print(arr_float)  # Output: [1. 2. 3.]


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[1. 2. 3.]


## Creating an array from a Python list:

In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)


[1 2 3 4 5]


## Creating a multidimensional array from nested lists:

In [ ]:
import numpy as np

my_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_array = np.array(my_list)
print(my_array)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Creating an array with a specified data type

In [ ]:
import numpy as np

my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list, dtype=np.float32)
print(my_array)


[1. 2. 3. 4. 5.]


## Creating an array with a range of values:

In [ ]:
import numpy as np

my_array = np.arange(1, 10, 2)
print(my_array)


[1 3 5 7 9]


## Creating an array with zeros:

In [ ]:
import numpy as np

my_array = np.zeros(5)
print(my_array)


[0. 0. 0. 0. 0.]


## Creating an array with ones:

In [ ]:
import numpy as np

my_array = np.ones((3, 4))
print(my_array)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# 2. Array Arithmetic

## Element-wise operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Addition
result = a + b  # [5, 7, 9]

# Subtraction
result = a - b  # [-3, -3, -3]

# Multiplication
result = a * b  # [4, 10, 18]

# Division
result = a / b  # [0.25, 0.4, 0.5]


## Scalar operations

In [ ]:
import numpy as np

a = np.array([1, 2, 3])

# Addition
result = a + 5  # [6, 7, 8]

# Subtraction
result = a - 2  # [-1, 0, 1]

# Multiplication
result = a * 3  # [3, 6, 9]

# Division
result = a / 2  # [0.5, 1.0, 1.5]


# Matrix Operations

## 1. Matrix multiplication (np.dot() or @ operator):

In [ ]:
import numpy as np

# Creating two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication using np.dot()
C = np.dot(A, B)
print("Matrix multiplication using np.dot():")
print(C)

# Matrix multiplication using @ operator (available in Python 3.5+)
C = A @ B
print("Matrix multiplication using @ operator:")
print(C)

Matrix multiplication using np.dot():
[[19 22]
 [43 50]]
Matrix multiplication using @ operator:
[[19 22]
 [43 50]]


## 2. Element-wise matrix multiplication (np.multiply() or * operator)

In [ ]:
import numpy as np

# Creating two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Element-wise matrix multiplication using np.multiply()
C = np.multiply(A, B)
print("Element-wise matrix multiplication using np.multiply():")
print(C)

# Element-wise matrix multiplication using * operator
C = A * B
print("Element-wise matrix multiplication using * operator:")
print(C)


Element-wise matrix multiplication using np.multiply():
[[ 5 12]
 [21 32]]
Element-wise matrix multiplication using * operator:
[[ 5 12]
 [21 32]]


## 3. Matrix exponentiation (np.linalg.matrix_power())


In [ ]:
import numpy as np

# Creating a matrix
A = np.array([[1, 2], [3, 4]])

# Matrix exponentiation using np.linalg.matrix_power()
C = np.linalg.matrix_power(A, 3)
print("Matrix exponentiation using np.linalg.matrix_power():")
print(C)


Matrix exponentiation using np.linalg.matrix_power():
[[ 37  54]
 [ 81 118]]


In [ ]:
import numpy as np

# Creating a 1D array
A = np.array([1, 2, 3])

# Matrix exponentiation for a 1D array
C = np.power(A, 3)
print("Exponentiation for a 1D array:")
print(C)


Exponentiation for a 1D array:
[ 1  8 27]


# NumPy Reshape

## 1. Reshaping a 1D array into a 2D array:

In [ ]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the 1D array into a 2D array with shape (2, 3)
b = a.reshape(2, 3)

print("Original array:")
print(a)
print("Reshaped array:")
print(b)


Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1 2 3]
 [4 5 6]]


In the example above, the `reshape()` function is used to reshape the 1D array a into a 2D array b with shape `(2, 3)`. The resulting array b has two rows and three columns.

## 2. Reshaping a 2D array into a 1D array:

In [ ]:
import numpy as np

# Creating a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Reshaping the 2D array into a 1D array
b = a.reshape(-1)

print("Original array:")
print(a)
print("Reshaped array:")
print(b)


Original array:
[[1 2 3]
 [4 5 6]]
Reshaped array:
[1 2 3 4 5 6]


In this example, the `reshape()` function is used to reshape the 2D array a into a 1D array b. The `-1` argument in the `reshape()` function indicates that the size of that dimension should be inferred based on the other dimensions and the total number of elements in the array.

## 3. Reshaping a 1D array into a column vector:

In [ ]:
import numpy as np

# Creating a 1D array
a = np.array([1, 2, 3, 4, 5, 6])

# Reshaping the 1D array into a column vector
b = a.reshape(-1, 1)

print("Original array:")
print(a)
print("Reshaped array:")
print(b)


Original array:
[1 2 3 4 5 6]
Reshaped array:
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In this example, the `reshape()` function is used to reshape the 1D array a into a column vector b by specifying `-1` for the number of rows and `1` for the number of columns. The resulting array b has six rows and one column.

In NumPy, when you use `.reshape()` on an array, you can specify the dimensions or shape you want for the reshaped array. In this case, `a` is the original array, and b is the reshaped array that will be assigned the result.

Now, let's break down `a.reshape(-1, 1)`:

a: The original array that you want to reshape.

`.reshape()`: A method in NumPy that allows you to change the shape of an array.

`-1`: In this context, -1 is a placeholder that tells NumPy to automatically calculate the size of the unspecified dimension based on the total number of elements in the original array. It infers the size to ensure the reshaped array has the same total number of elements.

`1`: Here `1` specifies the desired shape of the reshaped array. It means you want the reshaped array to have one column.

In [ ]:
row_vector = np.array([
                        [1, 2, 3]
                       ])    # shape (1, 3)

In [ ]:
col_vector = np.array([
                        [1, 2, 3]
                       ]).T  # shape (3, 1)

# Code Demo: Analyzing Sales Data

In [ ]:
import numpy as np

# Create a 2D NumPy array to represent the sales data for each product. 
# Each row represents a different product, and each column represents a different month.
sales_data = np.array([
                      [100, 120, 150, 200, 180],
                      [80, 90, 100, 110, 120],
                      [50, 60, 70, 80, 90]])

print(sales_data.shape)


(3, 5)


## Calculate the total sales for each product across all months using NumPy's sum() 

In [ ]:
total_sales = np.sum(sales_data, axis=1) # axis = 1 refers to horizontal axis
print("Total Sales for Each Product:")
print(total_sales)


Total Sales for Each Product:
[750 500 350]


## Calculate the average monthly sales for each product using NumPy's mean() function

In [ ]:
average_sales = np.mean(sales_data, axis=0) # axis = 0 refers to vertical axis
print("Average Monthly Sales for Each Product:")
print(average_sales)


Average Monthly Sales for Each Product:
[ 76.66666667  90.         106.66666667 130.         130.        ]


## Identify the month with the highest total sales using NumPy's argmax() function

In [ ]:
best_month_index = np.argmax(np.sum(sales_data, axis=0))
print("Month with Highest Total Sales:", best_month_index)


Month with Highest Total Sales: 3


## Identify the product with the highest average monthly sales using NumPy's argmax() function:

In [ ]:
best_product_index = np.argmax(np.mean(sales_data, axis=1)) 
print("Product with Highest Average Monthly Sales:", best_product_index)


Product with Highest Average Monthly Sales: 0


In [ ]:
np.mean(sales_data, axis=1)

array([150., 100.,  70.])

## Calculate the sales growth rate for each product from the first month to the last month using NumPy's pct_change() function:

In [ ]:
sales_growth = (sales_data[:, -1] - sales_data[:, 0]) / sales_data[:, 0]
print("Sales Growth Rate for Each Product:")
print(sales_growth)


Sales Growth Rate for Each Product:
[0.8 0.5 0.8]


In [ ]:
sales_data[:, -1]

array([180, 120,  90])

In [ ]:
sales_data[:, 0]

array([100,  80,  50])

In [ ]:
(sales_data[:, -1] - sales_data[:, 0]) / sales_data[:, 0]

array([0.8, 0.5, 0.8])

1 2 3 4 5
6 7 8 9 10
11 12 13 14 15
16 17 18 19 20
21 22 23 24 25


# NumPy `np.newaxis` 

## Example 1: Creating a column vector from a 1D array:

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Reshape the array into a column vector
column_vector = arr[:, np.newaxis]

print(column_vector)


[[1]
 [2]
 [3]
 [4]
 [5]]


## Example 2: Creating a row vector from a 1D array:

In [51]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Reshape the array into a row vector
row_vector = arr[np.newaxis, :]

print(row_vector)


[[1 2 3 4 5]]


## Example 3: Broadcasting an array with a scalar value

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Add a scalar value to the array using broadcasting
result = arr + 10

print(result)


[11 12 13 14 15]


## Example 4: Combining arrays of different dimensions using broadcasting:

In [ ]:
import numpy as np

column_vector = np.array([[1], [2], [3]])
row_vector = np.array([10, 20, 30])

# Perform element-wise multiplication using broadcasting
result = column_vector * row_vector[:, np.newaxis]

print(result)


[[10]
 [40]
 [90]]


In [ ]:
row_vector[:, np.newaxis].shape

(3, 1)